services:
    snowflake-proxy:
        network_mode: host
        image: containers.torproject.org/tpo/anti-censorship/pluggable-transports/snowflake:latest
        container_name: snowflake-proxy
        restart: unless-stopped
        # For a full list of Snowflake Proxy CLI parameters see
        # https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/snowflake/-/tree/main/proxy?ref_type=heads#running-a-standalone-snowflake-proxy
        #command: [ "-ephemeral-ports-range", "30000:60000" ]
    watchtower:
        image: containrrr/watchtower
        container_name: watchtower
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        command: snowflake-proxy
